openapi: 3.0.3
info:
  title: People API
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /people:
    get:
      summary: Получить список всех людей
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
          description: Количество записей для ограничения выборки
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
          description: Номер страницы (используется только вместе с limit)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllPeopleResponse'
        "400":
          description: Неверные параметры запроса

    post:
      summary: Создать новую запись
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "400":
          description: Bad Request
  /people/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Получить человека по ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "404":
          description: Not Found
    put:
      summary: Обновить данные человека по ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        "400":
          description: Bad Request
        "404":
          description: Not Found
    delete:
      summary: Удалить человека по ID
      responses:
        "204":
          description: No Content
components:
  schemas:
    Request:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        patronymic:
          type: string
      required:
        - name
        - surname

    Person:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        createdAt:
          type: string
          format: date-time
          example: "2025-06-09T12:34:56Z"
        updatedAt:
          type: string
          format: date-time
          example: "2025-06-10T08:21:00Z"
        name:
          type: string
          example: "Ivan"
        surname:
          type: string
          example: "Ivanov"
        patronymic:
          type: string
          example: "Ivanovich"
        age:
          type: integer
          format: int32
          description: "Возраст (если отсутствует в ответе — по умолчанию 0)"
          default: 0
        gender:
          type: string
          description: "Пол (если отсутствует в ответе — по умолчанию пустая строка)"
          default: ""
        nationality:
          type: string
          description: "Гражданство (если отсутствует в ответе — по умолчанию пустая строка)"
          default: ""
      required:
        - id
        - createdAt
        - updatedAt
        - name
        - surname

    AllPeopleResponse:
      type: object
      properties:
        people:
          type: array
          items:
            $ref: '#/components/schemas/Person'
